name: ml-games
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - pandas
    - matplotlib
    - scikit-learn
    - seaborn
    - statsmodels # recommended by seaboarn
    - numba
    - pymc3
    - torch 
    - torchvision